databases:
  - name: mysitedb
    plan: free
    databaseName:jsns_db
    user: akishino
services:
  - type: web
    plan: free
    name: jsns_service
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn j_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
        