# Generated by Django 5.1.2 on 2025-05-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    #    ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kairan', '回覧板'), ('keiji', '掲示板'), ('osirase', 'お知らせ')], max_length=50)),
                ('title', models.CharField(max_length=250, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
            ],
        ),
    ]
