# Generated by Django 5.2.1 on 2025-06-17 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kairan', '回覧板'), ('keiji', '掲示板'), ('osirase', 'お知らせ')], max_length=50)),
                ('title', models.CharField(max_length=250, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail3', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'j_sns_info',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント')),
                ('title', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='title_reviews', to='j_sns.info', verbose_name='タイトル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'j_sns_review',
            },
        ),
    ]
