# Generated by Django 5.1.2 on 2025-05-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j_sns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='files',
            field=models.ManyToManyField(blank=True, to='j_sns.file'),
        ),
        migrations.AddField(
            model_name='info',
            name='images',
            field=models.ManyToManyField(blank=True, to='j_sns.image'),
        ),
    ]
