# Generated by Django 5.1.2 on 2025-05-23 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j_sns', '0002_file_image_info_files_info_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='files',
        ),
        migrations.RemoveField(
            model_name='info',
            name='images',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kairan', '回覧板'), ('keiji', '掲示板'), ('osirase', 'お知らせ')], max_length=50)),
                ('title', models.CharField(max_length=250, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='コメント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
