# Generated by Django 5.1.2 on 2025-05-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j_sns', '0003_remove_info_files_remove_info_images_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(choices=[('kairan', '回覧板'), ('keiji', '掲示板'), ('osirase', 'お知らせ')], max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='category_reviews', to='j_sns.info'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='title_reviews', to='j_sns.info', verbose_name='タイトル'),
        ),
    ]
