# Generated by Django 5.1.2 on 2025-05-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j_sns', '0004_alter_review_category_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
