# Generated by Django 5.2.1 on 2025-06-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j_sns', '0010_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
